"""Extend relationship for MovieCompilation

Revision ID: 546cc5723944
Revises: f63498c1d99f
Create Date: 2024-04-04 16:03:05.182658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546cc5723944'
down_revision: Union[str, None] = 'f63498c1d99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_compilation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('enjoyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enjoyer_id'], ['enjoyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_comp_association_table',
    sa.Column('compilation_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compilation_id'], ['movie_compilation.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('compilation_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_comp_association_table')
    op.drop_table('movie_compilation')
    # ### end Alembic commands ###
